### PR TITLE
Version 0.0.6

### PR DESCRIPTION
**Pull request by tchellomello**
* Fixes for Melnor changes to wifieaquatimer.com #31 - @vanstinator 

Many thanks to @vanstinator  for your contribution and fixing the code after the update on Melnor website.

### CODE REVIEW

**Comment by tchellomello** [comment]
@vanstinator I've published the module into PyPi. 

Do you want to update the module within HA? 

Thank you!! :+1:

**Comment by vanstinator** [comment]
Yup! I'm going to run it locally for a day or two to make sure it all works great yet. After that I'll submit a PR

**Comment by vanstinator** [comment]
Alright. Just bumping the module didn't work. The integration itself isn't working either. I'm going to have to dig deeper 🤔

**Comment by vanstinator** [comment]
🤦‍♂️ my HA config was invalid. running well now 👍. Current road-map for me is:

1) submit PR that fixes the existing integration
2) update integration to use latest HA integration standards
3) add support for N controllers and N valves per account. (melnor currently hard-limits to 2. but that could change.)

**Comment by tchellomello** [comment]
Awesome @vanstinator Thanks for all your hard work!!

**Pull request merged**
